###############################################
# Run Github's Super Linter against code base #
###############################################

name: Github's Super Linter
on: push
  
jobs: 
  run-linters:
    name: Github's Super Linter
    runs-on: ubantu-latest
    
    steps: 
      - name: Check out Git repository      
        uses: actions/checkout@master
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_STANDARD: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
